version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-node-browsers
    working_directory: ~/AQA-Python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            curl -o allure-2.7.0.zip -Ls https://github.com/allure-framework/allure2/releases/download/2.7.0/allure-2.7.0.zip
            unzip allure-2.7.0.zip
            export PATH=$PATH:$(pwd)/allure-2.7.0/bin/
            echo "export PATH=$PATH:$(pwd)/allure-2.7.0/bin/" >> $BASH_ENV
            allure --version
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            chmod +x driver/chromedriver
            py.test -vv Tests/test_jira_ui.py -n 2 --dist=loadfile --driver Chrome --driver-path driver/chromedriver --alluredir=Tests/test_reports
            ./allure-2.7.0/bin/allure generate -c
      - store_artifacts:
          path: allure-report
          destination: allure-report

