version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-browsers
    working_directory: ~/aqapython
    steps:
     - checkout
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test_reports
          destination: test_reports