version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch-node-browsers
      - image: selenium/standalone-chrome:latest
    working_directory: ~/AQA-Python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - store_artifacts:
          path: test_reports
          destination: test_reports
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            chmod 755 driver/chromedriver
            py.test -vv Tests/test_jira_ui.py -n 2 --dist=loadfile --driver Chrome --driver-path $PATH:"driver/chromedriver"
